name: home-devcontainer

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSHD_PORT=2222
    privileged: true
    environment:
    # - SSH_PRIVATE_KEY=test
    ports:
      - 2223:2222
      - 2224:8080
    volumes:
      - mnt-dev:/mnt/dev
# - ~/.ssh/id_rsa:/tmp/SSH_PRIVATE_KEY:ro
# secrets: 
#   - SSH_PRIVATE_KEY
volumes:
  mnt-dev:
# secrets:
#   SSH_PRIVATE_KEY:
#     file: ~/.ssh/id_rsa
