name: home-devcontainer

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSHD_PORT=2222
    privileged: true
    ports:
      - 2223:2222
      - 2224:8080
    volumes:
      - mnt-dev:/mnt/dev
      - ~/.ssh/id_rsa:~/.ssh/id_rsa:ro
volumes:
  mnt-dev:
