name: 'Build/Publish'
run-name: 'Build/Publish : mgarnier11/devcontainer-basae:${{ github.ref_name }}'
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construction de l'image Docker
        env:
          TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
        run: |
          docker build \
          --file .devcontainer/Dockerfile \
          --tag mgarnier11/devcontainer-base:${{ github.sha }} \
          --tag mgarnier11/devcontainer-base:latest \
          .devcontainer

      - name: Publication de l'image Docker
        run: |
          docker login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password '${{ secrets.DOCKERHUB_TOKEN }}'
          docker push 'mgarnier11/devcontainer-base:${{ github.sha }}'
          docker push 'mgarnier11/devcontainer-base:latest'
          docker logout
